# Generated by Django 3.2.9 on 2022-08-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api07', '0002_alter_usertoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to='api07.userinfo'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=64, verbose_name='角色名称')),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='user_roles', to='api07.UserInfo')),
            ],
        ),
    ]
